backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://samgordon.design

# Comment this line out when pushing, uncomment while in dev and run: npx netlify-cms-proxy-server
# local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'post'
    label: 'Post'
    folder: 'content'
    format: 'frontmatter'
    identifier_field: number
    create: true
    slug: '{{number}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Number', name: 'number', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - { label: 'Image', name: 'image', widget: 'image', required: false }